"""add doc_ops and doc_snapshots

Revision ID: a03fd7252566
Revises: b4bd06b80678
Create Date: 2026-09-07 17:18:57.847764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03fd7252566'
down_revision: Union[str, Sequence[str], None] = 'b4bd06b80678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_ops',
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id', 'seq')
    )
    op.create_table('doc_snapshots',
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id', 'seq')
    )
    op.drop_constraint(op.f('ck_documents_visibility'), 'documents', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_documents_visibility'), 'documents', "visibility::text = ANY (ARRAY['private'::character varying, 'link'::character varying]::text[])")
    op.drop_table('doc_snapshots')
    op.drop_table('doc_ops')
    # ### end Alembic commands ###
